# CUDA_VISIBLE_DEVICES="4" python train.py --c /home/fengqianhan/qh-workspace/ssl-imb/config/classic_cv_imb/remixmatch_bacon/remixmatch_abcmcdrop_cifar10.yaml
algorithm: remixmatch
save_dir: ./saved_models/classic_cv_imb
save_name: remixmatch_bacon_cifar10
resume: True
load_path: /home/fengqianhan/qh-workspace/ssl-imb/saved_models/classic_cv_imb/remixmatch_bacon_cifar10/0250000_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 1000
num_train_iter: 300000
num_eval_iter: 1000
num_log_iter: 100
num_labels: 1000
batch_size: 64
eval_batch_size: 256
mixup_alpha: 0.75
T: 0.5
kl_loss_ratio: 0.5
ulb_loss_ratio: 1.5
rot_loss_ratio: 0.5
unsup_warm_up: 0.015625
uratio: 1
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False
data_dir: ./data
dataset: cifar10
train_sampler: RandomSampler
num_classes: 10
num_workers: 1
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10318
dist_backend: nccl
gpu: 0
include_lb_to_ulb: False
lb_imb_ratio: 100
ulb_imb_ratio: 100
ulb_num_labels: 4000
imb_algorithm: bacon
dist_align_target: uniform
abc_p_cutoff: 0.95
abc_loss_ratio: 1.0
